---
root: true
plugins:
  - node
extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:prettier/recommended

rules:
  semi: off
  node/no-missing-require: off
  no-unused-vars:
    - "error"
    - { argsIgnorePattern: "^_" }

parserOptions:
  sourceType: module
